#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { createRequire } from "node:module";

const SHADE_PAIRS = [
  [50, 950],
  [100, 900],
  [200, 800],
  [300, 700],
  [400, 600],
];

function parseColors(css) {
  const families = new Map();
  const re = /--color-([a-z]+)-(\d+):\s*([^;]+);/g;

  for (const [, family, shade, value] of css.matchAll(re)) {
    if (!families.has(family)) families.set(family, new Map());
    families.get(family).set(Number(shade), value.trim());
  }

  return families;
}

function invertShades(shades) {
  const inverted = new Map();

  for (const [light, dark] of SHADE_PAIRS) {
    const lightVal = shades.get(light);
    const darkVal = shades.get(dark);
    if (lightVal && darkVal) {
      inverted.set(light, darkVal);
      inverted.set(dark, lightVal);
    }
  }

  return inverted;
}

function generateCSS(families) {
  const lines = [
    "/* Generated by tailwind-dark-invert — do not edit manually */",
    "/* https://github.com/gonzaloandresoto/tailwind-dark-invert */",
    "",
    ".dark {",
  ];

  for (const [family, shades] of families) {
    const inverted = invertShades(shades);
    if (inverted.size === 0) continue;

    lines.push(`  /* ${family} */`);

    const sorted = [...inverted.entries()].sort(([a], [b]) => a - b);
    for (const [shade, value] of sorted) {
      lines.push(`  --color-${family}-${shade}: ${value};`);
    }

    lines.push("");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

// Resolve tailwindcss from the consumer's project, not from this package
const cwd = process.cwd();
const localRequire = createRequire(resolve(cwd, "package.json"));

let themePath;
try {
  themePath = localRequire.resolve("tailwindcss/theme.css");
} catch {
  console.error(
    "Error: Could not find tailwindcss in your project.\n" +
      "Make sure tailwindcss is installed:\n\n" +
      "  npm install tailwindcss\n"
  );
  process.exit(1);
}

const themeCSS = readFileSync(themePath, "utf-8");
const families = parseColors(themeCSS);
const css = generateCSS(families);

const outputFlag = process.argv.indexOf("-o");
const outputPath =
  outputFlag !== -1 ? process.argv[outputFlag + 1] : null;

if (outputPath) {
  writeFileSync(resolve(cwd, outputPath), css);
  const count = [...families.values()].reduce(
    (sum, s) => sum + s.size,
    0
  );
  console.log(
    `Generated ${outputPath} — ${families.size} color families, ${count} total shades`
  );
} else {
  process.stdout.write(css);
}
