import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const SHADE_PAIRS = [
  [50, 950],
  [100, 900],
  [200, 800],
  [300, 700],
  [400, 600],
];

/**
 * Parses all `--color-{family}-{shade}: {value};` declarations from Tailwind's
 * theme CSS and returns them grouped by color family.
 *
 * @returns {Map<string, Map<number, string>>} family -> shade -> value
 */
function parseColors(css) {
  const families = new Map();
  const re = /--color-([a-z]+)-(\d+):\s*([^;]+);/g;

  for (const [, family, shade, value] of css.matchAll(re)) {
    if (!families.has(family)) families.set(family, new Map());
    families.get(family).set(Number(shade), value.trim());
  }

  return families;
}

/**
 * Builds a shade -> value mapping where each shade is swapped with its mirror:
 * 50<->950, 100<->900, 200<->800, 300<->700, 400<->600.
 * Shade 500 stays unchanged.
 */
function invertShades(shades) {
  const inverted = new Map();

  for (const [light, dark] of SHADE_PAIRS) {
    const lightVal = shades.get(light);
    const darkVal = shades.get(dark);
    if (lightVal && darkVal) {
      inverted.set(light, darkVal);
      inverted.set(dark, lightVal);
    }
  }

  return inverted;
}

function generateCSS(families) {
  const lines = [
    "/* Generated by tailwind-dark-invert — do not edit manually */",
    "/* https://github.com/gonzalochale/tailwind-dark-invert */",
    "",
    ".dark {",
  ];

  for (const [family, shades] of families) {
    const inverted = invertShades(shades);
    if (inverted.size === 0) continue;

    lines.push(`  /* ${family} */`);

    const sortedShades = [...inverted.entries()].sort(
      ([a], [b]) => a - b
    );
    for (const [shade, value] of sortedShades) {
      lines.push(`  --color-${family}-${shade}: ${value};`);
    }

    lines.push("");
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

const themePath = require.resolve("tailwindcss/theme.css");
const themeCSS = readFileSync(themePath, "utf-8");
const families = parseColors(themeCSS);
const css = generateCSS(families);

writeFileSync(join(ROOT, "index.css"), css);

const count = [...families.values()].reduce(
  (sum, shades) => sum + shades.size,
  0
);
console.log(
  `Generated index.css — ${families.size} color families, ${count} total shades`
);
